version: '2'
  services:
    app:
      container_name: sample
      build:
        context: ./
        dockerfile: Dockerfile
      expose:
        - "8081"
      ports:
        - "8081:8081"
      restart: always