{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "java-azure-sample.serviceAccountName" . }}
  labels:
{{ include "java-azure-sample.labels" . | indent 4 }}
{{- end -}}
